const forbear = @import("forbear");

const Heading = @import("../heading.zig").Heading;
const Paragraph = @import("../paragraph.zig").Paragraph;

pub fn RegisteringGlobals() void {
    forbear.component(.{})({
        Heading(.{ .level = 1 })({
            forbear.text("Registering globals");
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.write("Registering globals with libwayland-server is done somewhat differently. When you generate \"server-code\" with wayland-scanner, it creates interfaces (which are analogous to listeners) and glue code for sending events. The first task is to register the global, with a function to rig up a ");
                forbear.Strong()({
                    forbear.write("resource");
                });
                forbear.write(" when the global is bound. In terms of code, the result looks something like this:");
            });
        });

        Paragraph(.{})({
            forbear.text("[code block omitted]");
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.write("If you take this code and, for example, patch it into the server example chapter 4.1, you'll make a ");
                forbear.Strong()({
                    forbear.write("wl_output");
                });
                forbear.write(" global visible to the \"globals\" program we wrote last time. However, any attempts to bind to this global will run into our TODO. To fill this in, we need to provide an ");
                forbear.Strong()({
                    forbear.write("implementation");
                });
                forbear.write(" of the ");
                forbear.Strong()({
                    forbear.write("wl_output");
                });
                forbear.write(" interface as well.");
            });
        });

        Paragraph(.{})({
            forbear.text("[code block omitted]");
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.write("This is a lot to take in, so let's explain it one piece at a time. At the bottom, we've extended our \"bind\" handler to create a ");
                forbear.Strong()({
                    forbear.write("wl_resource");
                });
                forbear.write(" to track the server-side state for this object (using the ID that the client allocated). As we do this, we provide ");
                forbear.Strong()({
                    forbear.write("wl_resource_create");
                });
                forbear.write(" with a pointer to our implementation of the interface ");
                forbear.Strong()({
                    forbear.write("&wl_output_implementation");
                });
                forbear.write(", a constant static struct in this file. The type (");
                forbear.Strong()({
                    forbear.write("struct wl_output_interface");
                });
                forbear.write(") is generated by wayland-scanner and contains one function pointer for each request supported by this interface. We also take the opportunity to allocate a small container for storing any additional state we need that libwayland doesn't handle for us, the specific nature of which varies from protocol to protocol.");
            });
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.Strong()({
                    forbear.write("Note:");
                });
                forbear.write(" there are two distinct things here which share the same name: ");
                forbear.Strong()({
                    forbear.write("struct wl_output_interface");
                });
                forbear.write(" is an instance of an interface, where ");
                forbear.Strong()({
                    forbear.write("wl_output_interface");
                });
                forbear.write(" is a global constant variable generated by wayland-scanner which contains metadata related to the implementation (such as version, used in the example above).");
            });
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.write("Our ");
                forbear.Strong()({
                    forbear.write("wl_output_handle_release");
                });
                forbear.write(" function is called when the client sends the ");
                forbear.Strong()({
                    forbear.write("release");
                });
                forbear.write(" request, indicating that they no longer need this resource — so we destroy it. This in turn triggers the ");
                forbear.Strong()({
                    forbear.write("wl_output_handle_resource_destroy");
                });
                forbear.write(" function, which later we'll extend to free any of the state we allocated for it earlier. This function is also passed into ");
                forbear.Strong()({
                    forbear.write("wl_resource_create");
                });
                forbear.write(" as the destructor, and will be called if the client terminates without explicitly sending the ");
                forbear.Strong()({
                    forbear.write("release");
                });
                forbear.write(" request.");
            });
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.write("The other remaining \"TODO\" in our code is to send the \"name\" event, as well as a few others. If we review ");
                forbear.Strong()({
                    forbear.write("wayland.xml");
                });
                forbear.write(", we see this event on the interface:");
            });
        });

        Paragraph(.{})({
            forbear.text("[code block omitted]");
        });

        Paragraph(.{})({
            forbear.text("It seems to be our responsibility to send this event when the output is bound. This is easy enough to add:");
        });

        Paragraph(.{})({
            forbear.text("[code block omitted]");
        });

        Paragraph(.{})({
            forbear.composeText(.{})({
                forbear.Strong()({
                    forbear.write("Note:");
                });
                forbear.write(" ");
                forbear.Strong()({
                    forbear.write("wl_output::geometry");
                });
                forbear.write(" is shown here for illustrative purposes, but in practice there are some special considerations for its use. Review the protocol XML before implementing this event in your client or server.");
            });
        });
    });
}
